spring:
  application:
    name: WRM
  datasource:
    url: jdbc:mysql://mysql:3306/wrm?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true